on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: paambaati/codeclimate-action@v3.0.0
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: npx jest --coverage
      - run: echo "ğŸ This job's status is ${{ job.status }}."
      - name: Test & publish code coverage
      - env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      - with:
          coverageCommand: make test-coverage
          debug: true
